[[params]]
title = "Gallery"

[[items]]
image = "static/artwork//flume.jpg"
thumb = "static/artwork//flume_thumb.jpg"
title = "flume"
materials = "acrylic on canvas panel"
size = "9x12"

[[items]]
image = "static/artwork//gazer.jpg"
thumb = "static/artwork//gazer_thumb.jpg"
title = "gazer"
materials = "acrylic on canvas"
size = "18x24"
